### ISSUE TITLE
Can you change SleekXMPP (dead project) to Slixmpp (Successor)

### ISSUE THREAD

**Issue by Neustradamus** [Dedas/dom4notify#1]
Can you update the code for compatibility with the successor of SleekXMPP?
- https://lab.louiz.org/poezio/slixmpp
- https://github.com/poezio/slixmpp

**Comment by Dedas** [comment]
I will look into it.

**Comment by Dedas** [comment]
New version for slixmpp released: https://github.com/Dedas/domnotify

**Comment by Neustradamus** [comment]
@Dedas: Thanks! :)

It was not easy to update directly here instead a new package name?

**Comment by Dedas** [comment]
No problem!

As I changed to both slixmpp and added support for Dominions 5 I felt that a new name was needed, one not tied to a specific game version. I'll probably archive this version.
